name: Update Revision Dates

on: gollum

jobs:
  updateWikiRevision:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      # Additional steps to generate documentation in "Documentation" directory
      - name: get wiki
        run: |
          git clone https://github.com/swsnu/swpp2020-team16.wiki.git
          cd swpp2020-team16.wiki
          git log -1 --stat > log.txt
          cat log.txt |  awk '{if(NR==2) print "author-["$2"]"; else if (NR==3) print "date-["$6" "$2" "$3" "$4" "$5"]"}' | awk 'NR%2{printf "%s ",$0;next;}1' > string.txt
          awk 'NR>2{while((getline a < "string.txt") > 0){print a}}1' Design-and-Planning.md > Design-and-Planning-revised.md
          cat Design-and-Planning.md
          echo revised-one
          cat Design-and-Planning-revised.md

          
        
#       - uses: actions/checkout@
#       - name: Run a one-line script
#         run: echo Hello, world!
