name: Update Revision Dates

on: gollum

jobs:
  updateRevision:
    runs-on: ubuntu-latest
    steps:
          - uses: actions/checkout@v2
          - name: Run a one-line script
            run: echo Hello, world!
