name: Update Revision Dates

on: gollum

jobs:
  updateWikiRevision:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      # Additional steps to generate documentation in "Documentation" directory
      - name: getWiki
        run: |
          git clone https://github.com/swsnu/swpp2020-team16.wiki.git
          ls
          cd  swpp2020-team16.wiki
          ls
          echo get wiki.
          
        
#       - uses: actions/checkout@
#       - name: Run a one-line script
#         run: echo Hello, world!
